version: '3'

services:
  app:
    # build: .
    build:
      context: .
      dockerfile: ./Dockerfile.development
    # env_file:
    #   - .env
    environment:
      RACK_ENV: development
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
    volumes:
      - .:/app:cached
      # - ${BASH_HISTORY_PATH:-~/.bash_history}:/root/.bash_history
      - bundle:/usr/local/bundle
      - rails_cache:/app/tmp/cache
      # - node_modules:/app/node_modules
      # - packs:/app/public/packs
      # exclude volumes below
      - /app/.git
      - /app/vendor
      - /app/tmp
      - /app/log
    depends_on:
      - db
    ports:
      - ${PORT:-3000}:3000
    tty: true
    stdin_open: true

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  cloud_sql_proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.16
    command:
      ["/cloud_sql_proxy",
      "-instances=cloudrun-rails-study:asia-northeast1:cloudrun-rails-study=tcp:0.0.0.0:3306",
      "-credential_file=/config/cloud-sql-proxy.json"]
      # ["/cloud_sql_proxy",
      # "-instances=[Cloud SQLのインスタンス名]=tcp:0.0.0.0:3306",
      # "-credential_file=/config/[サービスアカウントのJOSNファイル名]"]
    volumes:
      - "./keys/cloud-sql-proxy.json:/config/cloud-sql-proxy.json"
    ports:
      - ${CLOUD_SQL_PROXY_PORT:-3306}:3306

volumes:
  bundle:
  rails_cache:
  node_modules:
  # packs:
  db_data:
